# Generated by Django 3.2 on 2021-05-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210518_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
