# Generated by Django 3.2 on 2021-05-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hospital_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='state',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
