# Generated by Django 3.2 on 2021-05-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
    ]
